---
title: "Standard Deviation"
output: html_notebook
---
```{r message=FALSE, warning=FALSE, error=TRUE}
library(readr)
library(dplyr)
```

```{r error=TRUE}
load("project.Rda")
```

```{r error=TRUE}
# Change these variables to be the standard deviation of each dataset.
# Inspect Data
head(london_data)
#measurements were taken every 15 minutes
#useful columns include: Time, TemperatureC, Humidity, HourlyPrecipMM
nrow(london_data)

# Variance and SD for the year
temp <- london_data$TemperatureC
average_temp <- mean(temp)
average_temp
temperature_var <- var(temp)
print(temperature_var)
temperature_standard_deviation <- sd(temp)
print(temperature_standard_deviation)

#Inspect once again
head(london_data)
#month column will help us filter by month
june <- london_data %>%
filter(month=="06")

july <- london_data %>%
filter(month=="07")

# Get monthly temperature average
print(mean(june$TemperatureC))
print(mean(july$TemperatureC))

#Get monthly temperature Standard Deviation
print(sd(june$TemperatureC))
print(sd(july$TemperatureC))

# Analyze by month
monthly_stats_temp <- london_data %>%
    group_by(month) %>%
    summarize(mean = mean(TemperatureC),
              standard_deviation = sd(TemperatureC))
              
print(monthly_stats_temp)

#Analyze rainy months
monthly_stats_rain <- london_data %>%
    group_by(month) %>%
    summarize(mean = mean(dailyrainMM),
              standard_deviation = sd(dailyrainMM))
              
print(monthly_stats_rain)

#analyze rainy hours by month
hourly_stats_rain <- london_data %>%
    group_by(month, hour) %>%
    summarize(mean = mean(HourlyPrecipMM),
              standard_deviation = sd(HourlyPrecipMM))
              
print(hourly_stats_rain)
```